language: java
jdk:
  - openjdk8

branches:
  only:
    - boot

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - lolicol1@qq.com
    on_failure: always
    on_success: always
